# This is a basic workflow to help you get started with Actions

name: release-from-milestone

# Controls when the workflow will run
on:
  milestone:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Auto Release Milestone
      # You may pin to the exact commit or the version.
        id: create-release-milestone
        uses: ecampidoglio/auto-release-milestone@v1.0.0
        with:
        # The GITHUB_TOKEN used to authenticate to the current repository
           repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print the URL of the release draft
        if: steps.create-release-milestone.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
